from __future__ import annotations

from clinical_modules.schema_parser import ClinicalFieldSpec as F, ClinicalModuleSpec


def _spec(module_id: str, display_name: str, *fields: F) -> ClinicalModuleSpec:
    return ClinicalModuleSpec(module_id=module_id, display_name=display_name, fields=tuple(fields))


MODULE_SPECS: dict[str, ClinicalModuleSpec] = {
    "ENT": _spec(
        "ENT", "ENT 耳鼻喉檢查",
        F("nasal_septal_deviation", ("nasal septal deviation", "septal deviation", "鼻中膈偏曲", "鼻中隔偏曲"), "boolean"),
        F("inferior_turbinate_hypertrophy", ("inferior turbinate hypertrophy", "turbinate hypertrophy", "下鼻甲肥厚"), "boolean"),
        F("tonsil_hypertrophy", ("tonsil hypertrophy", "tonsil grade", "tonsil size", "扁桃腺肥大", "扁桃體肥大", "扁桃腺分級"), "int", minimum=0, maximum=4),
        F("soft_palate_abnormality", ("soft palate abnormality", "elongated soft palate", "軟顎異常", "軟腭異常", "軟顎延長"), "boolean"),
        F("mallampati", ("mallampati", "mallampati score", "mallampati class", "modified mallampati", "馬蘭帕蒂", "mallampati分級"), "int", minimum=1, maximum=4),
        F("nasal_obstruction", ("nasal obstruction", "nasal blockage", "鼻塞", "鼻腔阻塞"), "boolean"),
        F("adenoid_hypertrophy", ("adenoid hypertrophy", "腺樣體肥大", "腺样体肥大"), "boolean"),
        F("retrognathia", ("retrognathia", "mandibular retrognathia", "下顎後縮"), "boolean"),
        F("exam_date", ("exam date", "examination date", "檢查日期", "检查日期")),
    ),
    "DISE": _spec(
        "DISE", "DISE 藥物誘導睡眠內視鏡",
        F("velum_collapse", ("velum collapse", "velopharyngeal collapse", "軟顎塌陷", "軟腭塌陷")),
        F("oropharyngeal_lateral_wall_collapse", ("oropharyngeal lateral wall collapse", "lateral wall collapse", "口咽側壁塌陷", "口咽侧壁塌陷")),
        F("tongue_base_collapse", ("tongue base collapse", "舌根塌陷")),
        F("epiglottis_collapse", ("epiglottis collapse", "會厭塌陷", "会厌塌陷")),
        F("collapse_pattern", ("collapse pattern", "configuration", "塌陷型態", "塌陷模式"), choices=("anteroposterior", "lateral", "concentric", "mixed", "前後向", "側向", "同心性", "混合")),
        F("collapse_degree", ("collapse degree", "degree of collapse", "obstruction degree", "塌陷程度", "阻塞程度"), choices=("none", "partial", "complete", "無", "部分", "完全")),
        F("vote_classification", ("VOTE classification", "VOTE", "VOTE分類")),
        F("exam_date", ("exam date", "procedure date", "檢查日期", "检查日期")),
    ),
    "IMAGING": _spec(
        "IMAGING", "影像檢查（CT／CBCT／MRI）",
        F("modality", ("modality", "imaging modality", "影像類型", "檢查方式"), choices=("CT", "CBCT", "MRI", "cephalometry", "X-ray")),
        F("nasal_airway_narrowing", ("nasal airway narrowing", "nasal narrowing", "鼻腔狹窄", "鼻腔狭窄"), "boolean"),
        F("retropalatal_airway_narrowing", ("retropalatal airway narrowing", "retropalatal narrowing", "顎後氣道狹窄", "腭後氣道狹窄"), "boolean"),
        F("retroglossal_airway_narrowing", ("retroglossal airway narrowing", "retroglossal narrowing", "舌後氣道狹窄", "舌后气道狭窄"), "boolean"),
        F("craniofacial_abnormality", ("craniofacial abnormality", "retrognathia", "micrognathia", "顱顏異常", "下顎後縮", "小下顎"), "boolean"),
        F("other_anatomical_obstruction", ("other anatomical obstruction", "airway obstruction", "其他解剖阻塞", "其他氣道阻塞")),
        F("minimum_airway_area", ("minimum airway area", "minimum cross-sectional area", "MCA", "最小氣道截面積"), "float", "mm2", 0, 5000),
        F("airway_volume", ("airway volume", "upper airway volume", "氣道容積", "氣道體積"), "float", "mm3", 0, 100000),
        F("exam_date", ("exam date", "study date", "檢查日期", "检查日期")),
    ),
    "HYPOXEMIA": _spec(
        "HYPOXEMIA", "低氧來源評估",
        F("resting_spo2", ("resting SpO2", "daytime SpO2", "白天靜息血氧", "靜息SpO2"), "float", "%", 20, 100),
        F("exertional_spo2", ("exertional SpO2", "exercise SpO2", "活動血氧", "運動血氧"), "float", "%", 20, 100),
        F("supplemental_oxygen_required", ("supplemental oxygen required", "oxygen required", "需要氧氣", "需氧"), "boolean"),
        F("suspected_cause", ("suspected cause", "hypoxemia cause", "低氧原因", "疑似原因")),
    ),
    "ABG": _spec(
        "ABG", "血氣分析／CO₂",
        F("ph", ("pH", "血液pH"), "float", None, 6.5, 8.0),
        F("paco2", ("PaCO2", "arterial CO2", "動脈二氧化碳分壓"), "float", "mmHg", 10, 150),
        F("pao2", ("PaO2", "arterial O2", "動脈氧分壓"), "float", "mmHg", 10, 800),
        F("hco3", ("HCO3", "bicarbonate", "重碳酸鹽"), "float", "mmol/L", 0, 80),
        F("base_excess", ("base excess", "BE", "鹼剩餘"), "float", "mmol/L", -50, 50),
    ),
    "PULMONARY": _spec(
        "PULMONARY", "肺功能檢查",
        F("fev1_percent_predicted", ("FEV1 % predicted", "FEV1%pred", "FEV1預測值百分比"), "float", "%", 0, 200),
        F("fvc_percent_predicted", ("FVC % predicted", "FVC%pred", "FVC預測值百分比"), "float", "%", 0, 200),
        F("fev1_fvc_ratio", ("FEV1/FVC", "FEV1 FVC ratio", "一秒率"), "float", "%", 0, 100),
        F("dlco_percent_predicted", ("DLCO % predicted", "DLCO%pred", "DLCO預測值百分比"), "float", "%", 0, 200),
        F("obstructive_defect", ("obstructive defect", "阻塞型通氣障礙"), "boolean"),
        F("restrictive_defect", ("restrictive defect", "限制型通氣障礙"), "boolean"),
    ),
    "CARDIAC": _spec(
        "CARDIAC", "心臟與心血管評估",
        F("hypertension", ("hypertension", "高血壓"), "boolean"),
        F("heart_failure", ("heart failure", "心衰竭", "心臟衰竭"), "boolean"),
        F("coronary_artery_disease", ("coronary artery disease", "CAD", "冠狀動脈疾病"), "boolean"),
        F("atrial_fibrillation", ("atrial fibrillation", "AF", "心房顫動"), "boolean"),
        F("symptoms", ("cardiac symptoms", "symptoms", "心臟症狀")),
    ),
    "ECG": _spec(
        "ECG", "心電圖",
        F("rhythm", ("rhythm", "heart rhythm", "心律")),
        F("heart_rate", ("heart rate", "ventricular rate", "心率"), "float", "bpm", 10, 300),
        F("atrial_fibrillation", ("atrial fibrillation", "AF", "心房顫動"), "boolean"),
        F("conduction_abnormality", ("conduction abnormality", "傳導異常"), "boolean"),
        F("interpretation", ("interpretation", "impression", "判讀", "結論")),
    ),
    "ECHOCARDIOGRAPHY": _spec(
        "ECHOCARDIOGRAPHY", "心臟超音波",
        F("lvef", ("LVEF", "ejection fraction", "左心室射出分率"), "float", "%", 0, 100),
        F("pulmonary_artery_pressure", ("pulmonary artery pressure", "PASP", "肺動脈壓"), "float", "mmHg", 0, 200),
        F("right_ventricular_dysfunction", ("right ventricular dysfunction", "右心室功能異常"), "boolean"),
        F("valvular_disease", ("valvular disease", "瓣膜疾病"), "boolean"),
    ),
    "COMORBIDITY": _spec(
        "COMORBIDITY", "共病資料",
        *[F(name, aliases, "boolean") for name, aliases in (
            ("hypertension", ("hypertension", "高血壓")),
            ("heart_failure", ("heart failure", "心衰竭")),
            ("atrial_fibrillation", ("atrial fibrillation", "心房顫動")),
            ("coronary_artery_disease", ("coronary artery disease", "冠狀動脈疾病")),
            ("stroke", ("stroke", "cerebrovascular accident", "中風")),
            ("copd", ("COPD", "chronic obstructive pulmonary disease", "慢性阻塞性肺病")),
            ("asthma", ("asthma", "氣喘")),
            ("diabetes", ("diabetes", "糖尿病")),
            ("chronic_kidney_disease", ("chronic kidney disease", "CKD", "慢性腎臟病")),
            ("obesity", ("obesity", "肥胖")),
        )],
    ),
    "MEDICATION": _spec(
        "MEDICATION", "目前用藥",
        F("medication_list", ("medications", "medication list", "current medications", "目前用藥", "藥物清單")),
        F("sedative_hypnotics", ("sedative hypnotics", "benzodiazepine", "安眠藥", "鎮靜安眠藥"), "boolean"),
        F("opioids", ("opioids", "opioid", "鴉片類", "阿片類"), "boolean"),
        F("respiratory_depressants", ("respiratory depressants", "呼吸抑制藥物"), "boolean"),
        F("insomnia_diagnosis", ("insomnia diagnosis", "diagnosed insomnia", "失眠診斷", "失眠症"), "boolean"),
    ),
    "PATIENT_PREFERENCE": _spec(
        "PATIENT_PREFERENCE", "患者治療偏好",
        F("cpap_preference", ("CPAP preference", "偏好CPAP", "CPAP接受度")),
        F("apap_preference", ("APAP preference", "偏好APAP", "APAP接受度")),
        F("surgery_preference", ("surgery preference", "手術偏好", "接受手術")),
        F("medication_preference", ("medication preference", "藥物偏好")),
        F("primary_treatment_goal", ("primary treatment goal", "treatment goal", "主要治療目標")),
        F("accept_cpap", ("accept CPAP", "CPAP accepted", "接受CPAP"), "boolean"),
        F("accept_apap", ("accept APAP", "APAP accepted", "接受APAP"), "boolean"),
        F("accept_mad", ("accept MAD", "oral appliance accepted", "接受口內裝置"), "boolean"),
        F("accept_surgery", ("accept surgery", "surgery accepted", "接受手術"), "boolean"),
        F("accept_positional_therapy", ("accept positional therapy", "接受姿勢治療"), "boolean"),
        F("main_concern", ("main concern", "primary concern", "主要顧慮")),
        F("treatment_goal", ("treatment goal", "治療目標")),
    ),
    "FOLLOW_UP": _spec(
        "FOLLOW_UP", "治療追蹤資料",
        F("current_treatment", ("current treatment", "目前治療")),
        F("treatment_started_date", ("treatment started date", "start date", "治療開始日期")),
        F("symptom_improvement", ("symptom improvement", "症狀改善")),
        F("residual_ahi", ("residual AHI", "殘餘AHI", "治療後AHI"), "float", "events/hour", 0, 200),
        F("nightly_usage_hours", ("nightly usage hours", "usage hours", "每晚使用時數"), "float", "hours/night", 0, 24),
        F("adherence", ("adherence", "compliance", "依從性", "順從性")),
        F("tolerance", ("tolerance", "耐受度", "耐受性")),
        F("adverse_effects", ("adverse effects", "side effects", "副作用")),
        F("treatment_continued", ("treatment continued", "continue treatment", "持續治療"), "boolean"),
        F("follow_up_months", ("follow up months", "follow-up months", "追蹤月數"), "int", "months", 0, 120),
        F("weight_before_kg", ("weight before", "baseline weight", "治療前體重"), "float", "kg", 2, 500),
        F("weight_current_kg", ("current weight", "目前體重"), "float", "kg", 2, 500),
        F("weight_loss_kg", ("weight loss", "減重公斤"), "float", "kg", -300, 300),
        F("ess_before", ("ESS before", "baseline ESS", "治療前ESS"), "int", None, 0, 24),
        F("ess_current", ("current ESS", "follow-up ESS", "目前ESS"), "int", None, 0, 24),
        F("snoring", ("snoring", "打鼾")),
        F("daytime_sleepiness", ("daytime sleepiness", "日間嗜睡")),
        F("treatment_tolerance", ("treatment tolerance", "治療耐受度")),
    ),
    "ANTHROPOMETRY": _spec(
        "ANTHROPOMETRY", "身體測量資料",
        F("height_cm", ("height", "身高"), "float", "cm", 30, 250),
        F("weight_kg", ("weight", "體重"), "float", "kg", 2, 500),
        F("bmi", ("BMI", "body mass index", "身體質量指數"), "float", "kg/m2", 8, 100),
        F("neck_circumference_cm", ("neck circumference", "頸圍"), "float", "cm", 10, 100),
        F("waist_circumference_cm", ("waist circumference", "腰圍"), "float", "cm", 20, 250),
    ),
    "WEIGHT_MANAGEMENT": _spec(
        "WEIGHT_MANAGEMENT", "體重與減重紀錄",
        F("baseline_weight_kg", ("baseline weight", "初始體重"), "float", "kg", 2, 500),
        F("current_weight_kg", ("current weight", "目前體重"), "float", "kg", 2, 500),
        F("weight_change_kg", ("weight change", "體重變化"), "float", "kg", -300, 300),
        F("intervention", ("weight intervention", "weight management intervention", "減重介入", "體重管理方式")),
    ),
    "LIFESTYLE": _spec(
        "LIFESTYLE", "生活型態",
        F("smoking", ("smoking", "smoker", "吸菸", "抽菸")),
        F("alcohol_use", ("alcohol use", "drinking", "飲酒")),
        F("exercise", ("exercise", "physical activity", "運動")),
        F("sleep_schedule", ("sleep schedule", "睡眠作息")),
        F("shift_work", ("shift work", "輪班"), "boolean"),
    ),
    "SLEEP_QUESTIONNAIRE": _spec(
        "SLEEP_QUESTIONNAIRE", "睡眠問卷",
        F("ess_score", ("Epworth Sleepiness Scale", "ESS", "愛普沃斯嗜睡量表"), "int", None, 0, 24),
        F("stop_bang_score", ("STOP-BANG", "STOP BANG", "stopbang"), "int", None, 0, 8),
        F("isi_score", ("Insomnia Severity Index", "ISI", "失眠嚴重度指數"), "int", None, 0, 28),
        F("insomnia_diagnosis", ("insomnia diagnosis", "diagnosed insomnia", "失眠診斷", "失眠症"), "boolean"),
        F("psqi_score", ("Pittsburgh Sleep Quality Index", "PSQI", "匹茲堡睡眠品質指數"), "int", None, 0, 21),
    ),
    "DENTAL_CRANIOFACIAL": _spec(
        "DENTAL_CRANIOFACIAL", "牙科與顎顏面評估",
        F("retrognathia", ("retrognathia", "mandibular retrognathia", "下顎後縮"), "boolean"),
        F("micrognathia", ("micrognathia", "小下顎"), "boolean"),
        F("overjet_mm", ("overjet", "水平覆咬"), "float", "mm", -20, 30),
        F("tmj_disorder", ("temporomandibular disorder", "TMD", "顳顎關節障礙"), "boolean"),
        F("oral_appliance_candidate", ("oral appliance candidate", "MAD candidate", "口腔裝置適用"), "boolean"),
    ),
    "LABORATORY": _spec(
        "LABORATORY", "實驗室檢查",
        F("hemoglobin", ("hemoglobin", "Hb", "血紅素"), "float", "g/dL", 1, 30),
        F("hematocrit", ("hematocrit", "Hct", "血比容"), "float", "%", 1, 80),
        F("tsh", ("TSH", "thyroid stimulating hormone", "甲狀腺刺激素"), "float", None, 0, 200),
        F("hba1c", ("HbA1c", "glycated hemoglobin", "糖化血色素"), "float", "%", 2, 25),
        F("creatinine", ("creatinine", "Cr", "肌酸酐"), "float", "mg/dL", 0, 30),
    ),
    "NEUROLOGICAL": _spec(
        "NEUROLOGICAL", "神經學評估",
        F("neuromuscular_disease", ("neuromuscular disease", "神經肌肉疾病"), "boolean"),
        F("stroke_history", ("stroke history", "中風病史"), "boolean"),
        F("seizure_disorder", ("seizure disorder", "epilepsy", "癲癇"), "boolean"),
        F("neurological_findings", ("neurological findings", "神經學發現")),
    ),
    "PSYCHIATRIC": _spec(
        "PSYCHIATRIC", "心理與精神狀態",
        F("depression", ("depression", "憂鬱症", "抑鬱症"), "boolean"),
        F("anxiety", ("anxiety", "焦慮症"), "boolean"),
        F("ptsd", ("PTSD", "post-traumatic stress disorder", "創傷後壓力症"), "boolean"),
        F("psychiatric_medications", ("psychiatric medications", "精神科用藥")),
    ),
    "OXYGEN_THERAPY": _spec(
        "OXYGEN_THERAPY", "氧氣治療資料",
        F("oxygen_flow_lpm", ("oxygen flow", "flow rate", "氧氣流量"), "float", "L/min", 0, 30),
        F("delivery_method", ("oxygen delivery method", "delivery method", "給氧方式")),
        F("hours_per_day", ("oxygen hours per day", "hours per day", "每日使用時數"), "float", "hours/day", 0, 24),
        F("treatment_spo2", ("treatment SpO2", "oxygen SpO2", "治療血氧"), "float", "%", 20, 100),
    ),
    "SURGERY_HISTORY": _spec(
        "SURGERY_HISTORY", "手術與治療病史",
        F("procedure_name", ("procedure", "surgery", "手術名稱", "處置名稱")),
        F("procedure_date", ("procedure date", "surgery date", "手術日期")),
        F("outcome", ("outcome", "result", "手術結果", "治療結果")),
        F("complications", ("complications", "併發症")),
    ),
    "DEVICE_DATA": _spec(
        "DEVICE_DATA", "穿戴裝置或居家監測資料",
        F("device_name", ("device name", "device", "裝置名稱")),
        F("monitoring_period", ("monitoring period", "recording period", "監測期間")),
        F("estimated_ahi", ("estimated AHI", "REI", "估計AHI"), "float", "events/hour", 0, 200),
        F("minimum_spo2", ("minimum SpO2", "nadir SpO2", "最低血氧"), "float", "%", 20, 100),
        F("average_spo2", ("average SpO2", "mean SpO2", "平均血氧"), "float", "%", 20, 100),
        F("sleep_duration_hours", ("sleep duration", "sleep time", "睡眠時數"), "float", "hours", 0, 24),
        F("average_heart_rate", ("average heart rate", "mean HR", "平均心率"), "float", "bpm", 20, 250),
        F("minimum_heart_rate", ("minimum heart rate", "minimum HR", "最低心率"), "float", "bpm", 20, 250),
        F("maximum_heart_rate", ("maximum heart rate", "maximum HR", "最高心率"), "float", "bpm", 20, 250),
        F("average_respiratory_rate", ("average respiratory rate", "mean RR", "平均呼吸速率"), "float", "breaths/min", 2, 80),
        F("time_below_90_percent", ("time below 90 percent", "T90", "血氧低於90百分比"), "float", "%", 0, 100),
        F("apnea_event_count", ("apnea event count", "respiratory event count", "呼吸事件數"), "int", None, 0, 10000),
        F("rem_sleep_percent", ("REM sleep percent", "REM percentage", "REM百分比"), "float", "%", 0, 100),
        F("deep_sleep_percent", ("deep sleep percent", "N3 percentage", "深睡百分比"), "float", "%", 0, 100),
        F("supine_sleep_percent", ("supine sleep percent", "supine percentage", "仰睡百分比"), "float", "%", 0, 100),
        F("sensor_data_points", ("sensor data points", "sample count", "感測資料點數"), "int", None, 0, 10000000),
        F("sync_received_at", ("sync received at", "sync time", "同步時間")),
        F("data_source_type", ("data source type", "source type", "資料來源類型")),
    ),
    "OTHER": _spec(
        "OTHER", "其他臨床資訊",
        F("document_type", ("document type", "report type", "文件類型", "報告類型")),
        F("clinical_summary", ("clinical summary", "summary", "clinical note", "臨床摘要", "病歷摘要", "摘要")),
        F("assessment", ("assessment", "impression", "評估", "診斷印象")),
        F("plan", ("plan", "treatment plan", "計畫", "治療計畫")),
    ),
}


def get_module_spec(module_id: str) -> ClinicalModuleSpec:
    normalized = str(module_id).strip().upper()
    try:
        return MODULE_SPECS[normalized]
    except KeyError as exc:
        raise KeyError(f"找不到 Parser schema：{normalized}") from exc
